services:
  sql.server:
    environment:
      - SA_PASSWORD=P@ssword123!
      - ACCEPT_EULA=Y
    ports:
      - '5434:1433'

  volxyseat.payment:
    environment:
      - NODE_ENV=Production
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:80/health || exit 1"]
      interval: 10s
      retries: 10
      start_period: 15s
      timeout: 10s

  # volxyseat.api:
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Production
  #     - ASPNETCORE_URLS=http://+:80
  #     - ConnectionStrings__Homologation=TrustServerCertificate=True;Initial Catalog=VOLXYSEAT;User ID=SA;Password=P@ssword123!;Data Source=sql.server,1433;TrustServerCertificate=Yes
  #   ports:
  #     - '5239:80'
